name: ci build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234

        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        ls -a
        cd backend
        go mod tidy
        go mod vendor
        go build main.go

    - name: install psql
      run: |
        apt update -y
        apt install -y postgresql postgresql-contrib

    - name: migrate_database
      run: |
        cd backend/DB_scripts
        psql -h postgres "sslmode=disable user=postgres port=5432 password=1234" < create_test_db.sql
        psql -h postgres "sslmode=disable dbname=rsoi_persons_test user=postgres port=5432 password=1234" < create.sql
        psql -h postgres "sslmode=disable dbname=rsoi_persons_test user=postgres port=5432 password=1234" < fill_test_db.sql

    - name: Unit tests
      run: |
        cd backend/DA/DA_ut
        go test ./
